# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PedidoUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 912)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 133, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 55, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 510, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.botonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.botonEnviar.setGeometry(QtCore.QRect(440, 540, 91, 41))
        self.botonEnviar.setObjectName("botonEnviar")
        self.botonDel = QtWidgets.QPushButton(self.centralwidget)
        self.botonDel.setGeometry(QtCore.QRect(540, 540, 41, 41))
        self.botonDel.setObjectName("botonDel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 610, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(520, 610, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(440, 640, 181, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.botonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.botonAdd.setGeometry(QtCore.QRect(230, 10, 75, 23))
        self.botonAdd.setObjectName("botonAdd")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 470, 101, 16))
        self.label_4.setObjectName("label_4")
        self.BotonAdj = QtWidgets.QPushButton(self.centralwidget)
        self.BotonAdj.setGeometry(QtCore.QRect(20, 470, 75, 23))
        self.BotonAdj.setObjectName("BotonAdj")
        self.botonAdjT = QtWidgets.QPushButton(self.centralwidget)
        self.botonAdjT.setGeometry(QtCore.QRect(100, 470, 81, 23))
        self.botonAdjT.setObjectName("botonAdjT")
        self.BotonQuit = QtWidgets.QPushButton(self.centralwidget)
        self.BotonQuit.setGeometry(QtCore.QRect(190, 470, 81, 23))
        self.BotonQuit.setObjectName("BotonQuit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 100, 621, 361))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setMaxVisibleItems(20)
        self.comboBox_2.setObjectName("comboBox_2")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(190, 50, 21, 21))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(590, 610, 21, 21))
        self.toolButton_2.setObjectName("toolButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 540, 411, 291))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 21))
        self.menubar.setObjectName("menubar")
        self.menuConfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCorreo = QtWidgets.QAction(MainWindow)
        self.actionCorreo.setObjectName("actionCorreo")
        self.actionPesta_as = QtWidgets.QAction(MainWindow)
        self.actionPesta_as.setObjectName("actionPesta_as")
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.label.setBuddy(self.lineEdit)
        self.label_3.setBuddy(self.comboBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Articulo"))
        self.label_2.setText(_translate("MainWindow", "Pedido:"))
        self.botonEnviar.setText(_translate("MainWindow", "Enviar"))
        self.botonDel.setText(_translate("MainWindow", "B"))
        self.label_3.setText(_translate("MainWindow", "Destino:"))
        self.botonAdd.setText(_translate("MainWindow", "Agregar"))
        self.label_4.setText(_translate("MainWindow", "Nahuel Varela Blanco"))
        self.BotonAdj.setText(_translate("MainWindow", "Adjuntar"))
        self.botonAdjT.setText(_translate("MainWindow", "Adjuntar Todo"))
        self.BotonQuit.setText(_translate("MainWindow", "Quitar"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.menuConfiguracion.setTitle(_translate("MainWindow", "Configuracion"))
        self.actionCorreo.setText(_translate("MainWindow", "Correo"))
        self.actionPesta_as.setText(_translate("MainWindow", "Listas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

